name: Build and deploy Python app to Azure Web App - genbackend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Debug
        run: |
          pwd
          ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98179786092041829CB70EBA92F29818 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9D86EB36F6854ADE94AE6A8B17F9F8A3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2B3D5AF10F4A48B486F0433806CBBF54 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: genbackend
          slot-name: Production
